<?php
/**
 * Created by PhpStorm.
 * User: Volk
 * Date: 19.03.2019
 * Time: 2:29
 */

namespace app\models;


use yii\db\ActiveRecord;

class Article extends ActiveRecord{

    public static function tableName()
    {
        return 'articles'; // TODO: Change the autogenerated stub
    }

}
